### ISSUE TITLE
Updates to 1.3 docs

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1649]
This issue tracks updates that we made in 1.4 that also need to be backfilled into the 1.3 docs:

- [ ] [Ops user updates for docker cp](https://github.com/vmware/vic-product/commit/8068d45ffd66c4e320bf1545ba6cef057c8fb379)
- [ ] [Mention that grant perms doesn't work for standalone](https://github.com/vmware/vic-product/commit/e1a52709fb83fad2f3cc1ecc5ece13cc71262953)
- [ ] [Recommend using a DPG for public network rather than VM Network](https://github.com/vmware/vic-product/pull/1621)
- [ ] [Recommended recreating 1.2.x vApp VCHs](https://github.com/vmware/vic-product/pull/1646)
- [ ] [Reorganize TS info and improved linking](https://github.com/vmware/vic-product/pull/1628)
- [x] [Updated vRA support info](https://github.com/vmware/vic-product/pull/1627)
- [ ] [Add links to interop matrix](https://github.com/vmware/vic-product/pull/1626)
- [ ] [Replace link to pubs.vmware.com with docs.vmware.com](https://github.com/vmware/vic-product/pull/1595)
- [ ] [Info about NFS UID/GID and root user](https://github.com/vmware/vic-product/pull/1524)
- [ ] [Document what happens to a VCH when content trust is enabled on a project](https://github.com/vmware/vic-product/issues/1688)
- [ ] [Improve basic VCH deployment example](https://github.com/vmware/vic-product/issues/1612)
- [ ] [Add topic on Certificate Authority to DCH Photon to docs](https://github.com/vmware/vic-product/pull/1775)
- [ ] [Document what happens to a VCH when content trust is enabled on a project](https://github.com/vmware/vic-product/issues/1688)
- [ ] [Reinstate port numbers and protocol in Getting Started URLs](https://github.com/vmware/vic-product/issues/1824)
- [ ] [Document whether adding the same VCH to multiple projects is supported or not](https://github.com/vmware/vic-product/issues/1659)

**Comment by stuclem** [comment]
Actually, customers should have upgraded to 1.4.x by now. While this might be desirable, it's also time-consuming, so I elect not to do this.
